name: CI

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.3.0

      - name: Install dependencies and test
        env:
          node-version: '12.x'
          APP_NAME: ${{secrets.APP_NAME}}
          PORT: ${{secrets.PORT}}
          DB_CONN_STRING: ${{secrets.DB_CONN_STRING}}
          TESTDB_CONN_STRING: ${{secrets.TESTDB_CONN_STRING}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          JWT_LIFESPAN: ${{secrets.JWT_LIFESPAN}}
          MAILJET_EMAIL: ${{secrets.MAILJET_EMAIL}}
          MAILJET_PUBLIC_KEY: ${{secrets.MAILJET_PUBLIC_KEY}}
          MAILJET_PRIVATE_KEY: ${{secrets.MAILJET_PRIVATE_KEY}}
          ACCOUNT_ACTIVATION_EXPIRATION: ${{secrets.ACCOUNT_ACTIVATION_EXPIRATION}}
          RESET_PASSWORD_EXPIRATION: ${{secrets.RESET_PASSWORD_EXPIRATION}}
          REACTAPP_HOST: ${{secrets.REACTAPP_HOST}} 
        run: |
          npm run install:clean
          npm test --if-present
      
      - name: Check linting
        run: npm run lint

